### ISSUE TITLE
-webkit-linear-gradient won't be copied

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-webapp_DEPRECATED#590]
source css:

``` css
.toplead {
  background: linear-gradient(top, #3ab54b, #11ac68);
  background: -webkit-linear-gradient(top, #3ab54b, #11ac68);
}
```

=>

``` css
.toplead {
  background: linear-gradient(top, #3ab54b, #11ac68);
}
```
